### PR TITLE
review of issue_4, make changes for conciseness and clarity

### PR DESCRIPTION
**Pull request by KrishnaSannasi**

### CODE REVIEW

**Comment by Kylebrown9** [comment]
Overall I like idea to use the `?` operator and `fold` to accomplish the `get_view` behavior, however a fold where the initial value is a dummy being swapped out seems really sketchy. I've modified it back a little bit so that it still explicitly creates a proper first value, but by using `?` and `fold` it is still much more concise than the original.

I am ready to approve #14 and then #13 at this point. Let me know if you have any more changes or are good to go.

**Comment by KrishnaSannasi** [comment]
It's not a dummy variable, it has significance. It says that if the iterator contains no values, then None should be used. imo it is more clearly stating intent than your change.

**Comment by Kylebrown9** [comment]
The first argument to a fold indicates the base value being operated. I think indicating that the base value was `None` instead of `base_view` or a derivative of it is very confusing.

**Comment by KrishnaSannasi** [comment]
Ok, looks good

**Pull request merged**
