### PR TITLE
Issue 6

### PR DESCRIPTION
**Pull request by KrishnaSannasi**
This is a fix for #6, it regains `get` that returns a reference into the `Trie`

### CODE REVIEW

**Comment by Kylebrown9** [comment]
Is there a reason this doesn't use `std::convert::Into`?

**Comment by KrishnaSannasi** [comment]
Yes, I can't make a bound on `Trie::get` that would work if `Into<_>` is used.

Although something like

```rust
fn get<T, I>(self, path: I) -> Option<T>
        where
            I: IntoIterator<Item = K>,
            Self::View: Into<Option<T>>
```

would work, but that would lead to bad type inference, and it doesn't make sense to have multiple ways to convert a view into a value

**Comment by Kylebrown9** [comment]
I like the look of this, is there anyway to simplify `Option<<Self::View as TryIntoValue>::Value>` though?

**Comment by KrishnaSannasi** [comment]
It could be a type alias,

```rust
type Value<T> = <T as TryIntoValue>::Value;
```

then used as

```rust
Option<Value<Self::View>>
```

**Comment by KrishnaSannasi** [comment]
I made an update that works as I said in #6 [here](https://github.com/Randevelopment/Slang/issues/6#issuecomment-466668607). This should make the library more ergonomic, and easier to implement.

**Comment by Kylebrown9** [comment]
Nice! I like this pattern way more than the previous options. I'll review it a little more, and I'll probably merge it by end of day.

**Pull request merged**
